services:
  - type: web
    name: test-test-tes-crazy-ammme-ape
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y python3 python3-pip
      python3 -m pip install --upgrade pip
      python3 -m pip install --user yt-dlp
      npm install
    startCommand: |
      export PATH="$HOME/.local/bin:$PATH"
      export PYTHONPATH="$HOME/.local/lib/python3.*/site-packages:$PYTHONPATH"
      node server.js
