services:
  - type: web
    name: test-test-tes-crazy-ammme-ape
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y python3 python3-pip
      pip3 install --user yt-dlp
      npm install
    startCommand: |
      export PATH="$HOME/.local/bin:$PATH"
      node server.js
